FROM geonetwork:2.10-9.0
#FROM geonetwork:2.10-7.0

# image is debian 10, so client is psql 11
RUN apt-get update && apt-get install -y postgresql-client && \
    rm -rf /var/lib/apt/lists/*

# PostgreSQL as default GN DB

#Initializing database & connection string for GN

COPY ./docker-entrypoint-postgis.sh /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["catalina.sh", "run"]
