version: '2.2'

services:
    proxy:
        container_name: nginx4proxy
        hostname: proxy
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - nginx_proxy:/etc/nginx
volumes:
    nginx_proxy:
        name: nginx_proxy
