version: "3.6"
  services:
    couchdb:
      container_name: couchdb
      image: apache/couchdb:2.2.0
      restart: unless-stopped
      ports:
      - 5984:5984
      volumes:
      - ./test/couchdb/data:/opt/couchdb/data
      environment:
      - 'COUCHDB_USER=admin'
      - 'COUCHDB_PASSWORD=admin'

  couchdb_setup:
    depends_on: ['couchdb']
    container_name: couchdb_setup
    image: apache/couchdb:2.2.0
    command: ['/bin/bash', '-x', '-c', 'cat /usr/local/bin/couchdb_setup.sh | tr -d "\r" | bash']
    volumes:
    - ./scripts/couchdb_setup.sh:/usr/local/bin/couchdb_setup.sh:ro
    environment:
    - 'COUCHDB_USER=admin'
    - 'COUCHDB_PASSWORD=password'
