#
# maintainer: "Alvaro Barcellos <alvaro.barcellos@cprm.gov.br>"
#

version: "2.2"

networks:
    default:
    services:
        external: true

services:
  
    geonetwork_2.10-9.0:
        build: 
            context: ./
            dockerfile: Dockerfile_${COMPOSE_PROJECT_NAME}
        image: ${COMPOSE_PROJECT_NAME}:${SET_DOCKER_TAG}
        container_name: ${COMPOSE_PROJECT_NAME}-${SET_DOCKER_TAG}
        restart: unless-stopped
        stdin_open: true
        # tty: true
        labels:
            org.${COMPOSE_PROJECT_NAME}.component: ${COMPOSE_PROJECT_NAME}
            org.instance.name: ${COMPOSE_PROJECT_NAME}
        ports:
            - ${SET_DOCKER_PORT}
        volumes:
            - volume_datadir:/var/lib/${COMPOSE_PROJECT_NAME}/_data
        environment:
            ${COMPOSE_PROJECT_NAME}_DEFAULT_EMAIL: admin@example.com
        networks:
            - default
            - services

volumes:
    volume_datadir:
        name: ${COMPOSE_PROJECT_NAME}-datadir-${SET_DOCKER_TAG}

